### ISSUE TITLE
TypeError: app.use() requires middleware functions

### ISSUE THREAD

**Issue by kenroy** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#17]
I'm working on the adding user accounts section and I get the error below when I try to start the server. It seems to not like the .use(users) in server.js. Any idea how to fix this?

Thanks,
Kenroy

/opt/web/ngApp/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/opt/web/ngApp/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/opt/web/ngApp/server.js:8:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
18 Sep 21:32:32 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by kenroy** [comment]
Problem solved. I forgot module.exports = router in accounts.js
