### ISSUE TITLE
Bourne Error

### ISSUE THREAD

**Issue by FadelChafai** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#2]
Hi

When i start the server i have an error, its about bourne 

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at new Bourne (/usr/lib/node_modules/bourne/lib/bourne.js:52:30)
    at Object.<anonymous> (/var/www/angular/app/api.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/angular/app/server.js:3:9)
11 Oct 21:32:28 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by magalhini** [comment]
@khuezy Thank you so much, I would never guess that that was the issue. I had the json file created but it was empty — I was about to go mental!

**Comment by elouafir** [comment]
I had the same error thanks

**Comment by andrew8088** [comment]
Yeah, it's a bug in Bourne. Easiest way to fix it is to stop the server, delete your .json file, and restart the server.
